Display page title instead of menu title
django-cms/djangocms-link pull request #194
Opened 2021-08-03 10:08 UTC by adrien-delhorme

The default label for select2 items are the Page's [`__str__` method](https://github.com/django-cms/django-cms/blob/develop/cms/models/pagemodel.py#L256), which displays the page's menu title.

It happens frequently that several pages share the same menu title: they are therefore indistinguishable from each other.

This pull request displays the page's title instead of the menu title.

2021-08-03 11:42 UTC, adrien-delhorme commented
Duplicate of my pull-request #193 :zany_face:

2021-08-03 22:58 UTC, marksweb approved these changes

2022-02-23 11:57 UTC, marksweb requested changes
@adrien-delhorme could you please add an entry in the changelog under an "Unreleased" title for this?

2022-02-24 15:01 UTC, adrien-delhorme commented
Sure! (done)

2022-02-24 15:02 UTC, marksweb commented
@adrien-delhorme fantastic, thank you!

2022-02-24 15:03 UTC, marksweb approved these changes

2022-03-17 00:48 UTC, merged